config/routes.rb
Rails.application.routes.draw do
  
  	root 'home#index'

	resources :gift_lists do
		collection do
		get 'add_products/:gift_list_id/', :to => "gift_lists#add_products", :as => 'add_product'
		end
	end

  	resources :gift_lists_suggestions 

	resources :products 
	get '/search', to: 'search#index'

	resources :user_stores do
		collection do
			post 'create/:product_id', :to => "user_stores#create", :as => 'add_product'
			delete 'delete/:id/', :to => "user_stores#destroy", :as => 'delete_product'
		end
	end
  
  	resources :apps, only: :show
  
	namespace :api do
		namespace :v1 do 
     		resources :products, only: [:index]
    	end 
	end 
	  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    def to_s
        self.name
    end
end

app/models/gift_list.rb
class GiftList < ApplicationRecord
end

app/models/gift_list_store.rb
class GiftListStore < ApplicationRecord
    belongs_to :user
    belongs_to :gift_list
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true, length: { maximum: 100 }
    validates :description, presence: true, length: { maximum: 1000 }
    VALID_PRICE_REGEX = /\A\d+(?:\.\d{0,3})?\z/
    validates :price, presence: true, :format => { with: VALID_PRICE_REGEX }, :numericality => {:greater_than => 0}
    
    validates_uniqueness_of :name

    belongs_to :category

    has_many :users, through: :user_stores

    def to_s
        self.name
    end

    def category_name
        self.category.name.to_s
    end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_stores
  	has_many :products, through: :user_stores
end

app/models/user_store.rb
class UserStore < ApplicationRecord
    belongs_to :user
    belongs_to :product
    
    validates :product_id, uniqueness: { message: "Erro: Produto já guardado." }
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController

	def index
		
		begin
			products = Product.page(params[:page]).per(15)

			total = Product.all.count
			
			render json: products, 
				except: [:created_at, :updated_at], 
			  	include: {
					category: {
						except: [:created_at, :updated_at]
					}
				},
				meta: {
             		pagination: {
               			per_page: 15,
               			total_pages: total / 15,
               			total_objects: total
             		}
           		}, status: :ok
		rescue
			head :internal_server_error
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show]

	def show
  	end

  	private
    def set_app
      @app = Product.find(params[:id])
	end
	
end

app/controllers/gift_lists_controller.rb
class GiftListsController < ApplicationController
    before_action :set_gift_list, only: [:edit, :update, :destroy]

    def index
        @my_gift_lists = GiftList.where(suggestion: false)
    end

    def new
        @gift_list = GiftList.new
    end

    def show
        @gift_list = GiftList.find(params[:id])
        @products = Product.order(category_id: :desc).limit(8)
    end

    def create
        @gift_list = GiftList.new(params_gift_list)

        respond_to do |format|
            if @gift_list.save
              format.html { redirect_to gift_lists_path, flash: { success: 'Lista criada com sucesso.' }}
            else
              format.html { redirect_to gift_lists_path, flash: { error: @gift_list.errors.full_messages.first }}
            end
        end
    end

    def add_products
        @gift_list = GiftList.find(params[:gift_list_id])
        @product_store = User.first.products
    end

    private
    def params_gift_list
        params.require(:gift_list).permit(:name, :date_event, :suggestion)
    end

    def set_gift_list
        @gift_list = GiftList.find(params[:id])
    end
    
end

app/controllers/gift_lists_suggestions_controller.rb
class GiftListsSuggestionsController < ApplicationController
  
	def show
   		@gift_list = GiftList.find(params[:id])
   		@products = Product.order(category_id: :desc).limit(8)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@most_selected = GiftList.where(suggestion: true).order("RANDOM()").limit(8)
		@best_prices = GiftList.where(suggestion: true).order("RANDOM()").limit(4)
  	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
	def index
    	@most_selected = Product.order(category_id: :desc).limit(4)
    	@best_prices = Product.order(price: :desc).limit(4)
		@products = Product.all
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
    	@apps = Product.where("name LIKE ?", "%#{params[:query]}%")
  	end

end

app/controllers/user_stores_controller.rb
class UserStoresController < ApplicationController

	def show
    	@product_store = User.first.products
	end
	
	def create
        @store = UserStore.new(user_id: User.first.id, product_id: params[:product_id])
        
        respond_to do |format|
        	if @store.save
            	format.html { redirect_to products_path, flash: { success: 'Produto guardado com sucesso.' }}
          	else
            	format.html { redirect_to products_path, flash: { error: @store.errors.full_messages.first }}
          	end
        end
    end

	def destroy
    	@store = UserStore.find_by_product_id(params[:id])
		@store.destroy
		
		respond_to do |format|
			format.html { redirect_to user_store_path, flash: { success: 'Produto removido com sucesso.' }}
		end
	end

    private
    def user_store_params
    	params.fetch(:product_id, :id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when 'error' then "ui red message"
            when 'success' then "ui green message"
            when 'info' then "ui blue message"
        end
      end
end

app/helpers/apps_helper.rb
module AppsHelper
  require 'digest/md5'

  def product_image(product)
    color = Digest::MD5.hexdigest(product.name)[0..5]
    "https://dummyimage.com/300x300/#{color}/ffffff.png&text=#{product.name}"
  end
end

app/helpers/gift_lists_helper.rb
module GiftListsHelper
end

app/helpers/gift_lists_suggestions_helper.rb
module GiftListsSuggestionsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/user_store_helper.rb
module UserStoreHelper
end

app/views/gift_lists/_gift_list_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four link cards">
	<% my_gift_lists.each do |my_gift_list| %>
		
		<a class="card" href="<%= app_path(my_gift_list) %>">
			<div class="image">
				<img src="<%= product_image(my_gift_list) %>">
			</div>

			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						<%= my_gift_list.name %> dsdsds
					</div>
				</div>
			</div>
		</a>

	<% end %>
</div>

app/views/gift_lists/_product_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four cards">
	<% product_list.each do |product| %>

		<div class="card">
			<div class="image">
				<img src="<%= product_image(product) %>">
			</div>
			<div class="content">
				<div class="header"><%= product.name %></div>
				<div class="meta"><%= product.category %></div>
				<div class="description"><%= truncate product.description, length: 100, seperator: /\w+/ %></div>
			</div>
			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						R$ <%= number_to_human product.price %>
					</div>
				</div>
			</div>
			<div class="ui bottom attached button">
				<i class="orange add icon"></i>
				Adicionar Produto à Lista
			</div>
		</div>
		
	<% end %>
</div>

app/views/gift_lists/_product_list_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four cards">
	<% product_list.each do |product| %>

		<div class="card">
			<div class="image">
				<img src="<%= product_image(product) %>">
			</div>
			<div class="content">
				<div class="header"><%= product.name %></div>
				<div class="meta"><%= product.category %></div>
				<div class="description"><%= truncate product.description, length: 100, seperator: /\w+/ %></div>
			</div>
			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						R$ <%= number_to_human product.price %>
					</div>
				</div>
			</div>
			<div class="ui bottom attached button">
				<i class="orange remove icon"></i>
				Remover Produto da Lista
			</div>
		</div>
		
	<% end %>
</div>

app/views/gift_lists/add_products.html.erb
<h1 class="ui orange block header">
	<i class="orange gift icon"></i>
	<div class="content">
		Adicionar MEUS PRODUTOS GUARDADOS
		<div class="sub header">Adicionar produtos guardados à minha lista de presentes.</div>
	</div>
</h1>

<div class="ui padded center aligned raised segment">
	<h2 class="ui center aligned icon header">
		<i class="circular users icon"></i>
		<%= @gift_list.name %>
	</h2>
</div>

<%= render partial: "gift_lists/product_cards", locals: { name: "Meus Produtos Guardados", product_list: @product_store } %>

app/views/gift_lists/index.html.erb
<div class="ui container content">
	<h1 class="ui orange block header">
		<i class="orange list icon"></i>
		<div class="content">
			Minhas Listas
			<div class="sub header">Minhas listas cadastradas.</div>
		</div>
	</h1>
</div>

<div class="ui container content center aligned">
	<div class="ui raised segment">
		<%= button_to 'Crie a sua lista do zero', new_gift_list_path, class: 'positive ui big button', method: :get %>
		<h3 class="ui header orange">
			Você poderá escolher todos seus presentes
		</h3>
	</div>
</div>

<div class="ui raised segment two column grid">
	<% @my_gift_lists.each do |my_gift_list| %>
	
		<div class="column">
			<div class="ui padded center aligned raised segment">
				<h2 class="ui center aligned icon header">
					<i class="circular users icon"></i>
					<%= my_gift_list.name %>
				</h2>
				<div class="ui buttons">
					<%= button_to 'VER PRODUTOS', gift_list_path(my_gift_list.id), class: 'ui button', method: :get %>
					<div class="or"></div>
					<button class="ui positive button">COMPARTILHAR</button>
				</div>
			</div>
		</div>

	<% end %>
</div>

app/views/gift_lists/new.html.erb
<h1 class="ui orange block header">
    <i class="orange list icon"></i>
    <div class="content">
        Criar Lista
        <div class="sub header">Você está criando uma lista do zero.</div>
    </div>
</h1>

<div class="ui padded raised segment">
    <%= render partial: 'gift_lists/shared/form' %>
</div>

app/views/gift_lists/shared/_form.html.erb
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>

<script>
    $(document).ready(function () {
        $('#gift_list_date_event').mask('99/99/9999');
        return false;
    });
</script>

<% if @gift_list.errors.any? %>
    <div class="ui orange message">
        <ul class="list">
            <% @gift_list.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="ui raised segment">
    <div class="ui form">
        <%= form_with(model: [ @gift_list ], local: true) do |form| %>
            
            <%= form.hidden_field :suggestion, value: false  %>
            
            <div class="two fields">
                <div class="field">
                    <label>Nome</label>
                    <%= form.text_field :name, placeholder: 'Informe o nome'  %>
                </div>
                <div class="field">
                    <label>Data Evento</label>
                    <%= form.text_field :date_event, placeholder: 'Informe a data do evento'  %>
                </div>
            </div>
            <button type="submit" class="ui positive button">
                Salvar
            </button>

        <% end %>
    </div>
</div>

app/views/gift_lists/show.html.erb
<h1 class="ui orange block header">
	<i class="orange list icon"></i>
	<div class="content">
		Minha Lista
		<div class="sub header">Minha lista personalizada.</div>
	</div>
</h1>

<div class="ui padded center aligned raised segment">
	<h2 class="ui center aligned icon header">
		<i class="circular users icon"></i>
		<%= @gift_list.name %>
	</h2>
	<div class="ui buttons">
		<%= button_to 'ADICIONAR MEUS PRODUTOS', add_product_gift_lists_path(@gift_list.id), class: 'ui button', method: :get %>
		<div class="or"></div>
		<button class="ui positive button">COMPARTILHAR</button>
	</div>
</div>

<%= render partial: "gift_lists/product_list_cards", locals: { name: "Produtos da Minha Lista (Produtos Estáticos)", product_list: @products } %>

app/views/gift_lists_suggestions/_gift_list_suggestions_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four link cards">
	<% suggestion_lists.each do |suggestion_list| %>

		<a class="card" href="/gift_lists_suggestions/1">
			<div class="image">
				<img src="<%= product_image(suggestion_list) %>">
			</div>
			<div class="content center aligned">
				<div class="header"><%= suggestion_list.name %></div>
				<div class="meta"><%= rand(9..67) %> Itens</div>
			</div>
			
			<div class="ui bottom attached button">
				<i class="orange search icon"></i>
				Ver Produtos
			</div>
		</a>
		
	<% end %>
</div>

app/views/gift_lists_suggestions/_product_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four cards">
	<% product_list.each do |product| %>

		<div class="card">
			<div class="image">
				<img src="<%= product_image(product) %>">
			</div>
			<div class="content">
				<div class="header"><%= product.name %></div>
				<div class="meta"><%= product.category %></div>
				<div class="description"><%= truncate product.description, length: 100, seperator: /\w+/ %></div>
			</div>
			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						R$ <%= number_to_human product.price %>
					</div>
				</div>
			</div>
		</div>
		
	<% end %>
</div>

app/views/gift_lists_suggestions/show.html.erb
<h1 class="ui orange block header">
	<i class="orange list icon"></i>
	<div class="content">
		Sugestão de Lista
		<div class="sub header">Você poderá dar um nome exclusivo e escolher uma foto dos seus arquivos.</div>
	</div>
</h1>

<div class="ui padded center aligned raised segment">
	<h2 class="ui center aligned icon header">
		<i class="circular users icon"></i>
		Sou Super Herói (Página Estática)
	</h2>
	<div class="ui buttons">
		<button class="ui button">QUERO ESSA LISTA PRÉ PRONTA</button>
		<div class="or"></div>
		<%= button_to 'QUERO CRIAR UMA LISTA DO ZERO', new_gift_list_path, class: 'positive ui button', method: :get %>
	</div>
</div>

<%= render partial: "gift_lists_suggestions/product_cards", locals: { name: "Produtos",product_list: @products } %>

app/views/products/index.html.erb
<h1 class="ui orange block header">
	<i class="orange gift icon"></i>
	<div class="content">
		Produtos
		<div class="sub header">Guarde seus produtos favoritos para criar suas listas no futuro.</div>
	</div>
</h1>

<h2 class="ui orange header">Pesquisar Produtos</h3>
<div class="ui divider"></div>
<%= react_component("Search", prerender: true) %>

<h2 class="ui orange header">Categorias de Produtos</h3>
<div class="ui divider"></div>

<div class="ui raised segment search-container">
	<%= react_component("Categories", prerender: true) %>
</div>

<%= render partial: "apps/app_cards", locals: { name: "Mais Escolhidos", app_list: @most_selected } %>
<%= render partial: "apps/app_cards", locals: { name: "Ótimo Preços", app_list: @best_prices } %>

app/views/user_stores/_product_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four cards">
	<% products_list.each do |product_list| %>

		<div class="card">

			<div class="image">
				<img src="<%= product_image(product_list) %>">
			</div>

			<div class="content">
				<div class="header"><%= product_list.name %></div>
				<div class="meta"><%= product_list.category %></div>
				<div class="description"><%= truncate product_list.description, length: 100, seperator: /\w+/ %></div>
			</div>

			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						R$ <%= number_to_human product_list.price %>
					</div>
				</div>
			</div>

			<%= link_to delete_product_user_stores_path(product_list.id), method: :delete, data: { confirm: 'Deseja Remover o Produto?' } do %>
				<div class="ui bottom attached button">
					<i class="orange remove icon"></i>
					Remover Produto
				</div>
			<% end %>

		</div>

	<% end %>
</div>

app/views/user_stores/show.html.erb
<h1 class="ui orange block header">
	<i class="orange gift icon"></i>
	<div class="content">
		Meus Produtos
		<div class="sub header">Aqui estão os produtos guardados para crição de suas listas.</div>
	</div>
</h1>

<%= render partial: "user_stores/product_cards", locals: { name: "Lista de Produtos", products_list: @product_store } %>