config/routes.rb
Rails.application.routes.draw do
  
  	root 'home#index'

	resources :gift_lists do
		collection do
		get 'add_products/:gift_list_id/', :to => "gift_lists#add_products", :as => 'add_product'
		end
	end

  	resources :gift_lists_suggestions 

	resources :products 
	get '/search', to: 'search#index'

	resources :user_stores do
		collection do
			post 'create/:product_id', :to => "user_stores#create", :as => 'add_product'
			delete 'delete/:id/', :to => "user_stores#destroy", :as => 'delete_product'
		end
	end
  
  	resources :apps, only: :show
  
	namespace :api do
		namespace :v1 do 
     		resources :products, only: [:index]
    	end 
	end 
	  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    def to_s
        self.name
    end
end

app/models/gift_list.rb
class GiftList < ApplicationRecord
end

app/models/gift_list_store.rb
class GiftListStore < ApplicationRecord
    belongs_to :user
    belongs_to :gift_list
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true, length: { maximum: 100 }
    validates :description, presence: true, length: { maximum: 1000 }
    VALID_PRICE_REGEX = /\A\d+(?:\.\d{0,3})?\z/
    validates :price, presence: true, :format => { with: VALID_PRICE_REGEX }, :numericality => {:greater_than => 0}
    
    validates_uniqueness_of :name

    belongs_to :category

    has_many :users, through: :user_stores

    def to_s
        self.name
    end

    def category_name
        self.category.name.to_s
    end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_stores
  	has_many :products, through: :user_stores
end

app/models/user_store.rb
class UserStore < ApplicationRecord
    belongs_to :user
    belongs_to :product
    
    validates :product_id, uniqueness: { message: "Erro: Produto já guardado." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show]

	def show
  	end

  	private
    def set_app
      @app = Product.find(params[:id])
	end
	
end

app/controllers/gift_lists_controller.rb
class GiftListsController < ApplicationController
    before_action :set_gift_list, only: [:edit, :update, :destroy]

    def index
        @my_gift_lists = GiftList.where(suggestion: false)
    end

    def new
        @gift_list = GiftList.new
    end

    def show
        @gift_list = GiftList.find(params[:id])
        @products = Product.order(category_id: :desc).limit(8)
    end

    def create
        @gift_list = GiftList.new(params_gift_list)

        respond_to do |format|
            if @gift_list.save
              format.html { redirect_to gift_lists_path, flash: { success: 'Lista criada com sucesso.' }}
            else
              format.html { redirect_to gift_lists_path, flash: { error: @gift_list.errors.full_messages.first }}
            end
        end
    end

    def add_products
        @gift_list = GiftList.find(params[:gift_list_id])
        @product_store = User.first.products
    end

    private
    def params_gift_list
        params.require(:gift_list).permit(:name, :date_event, :suggestion)
    end

    def set_gift_list
        @gift_list = GiftList.find(params[:id])
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@most_selected = GiftList.where(suggestion: true).order("RANDOM()").limit(8)
		@best_prices = GiftList.where(suggestion: true).order("RANDOM()").limit(4)
  	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
	def index
    	@most_selected = Product.order(category_id: :desc).limit(4)
    	@best_prices = Product.order(price: :desc).limit(4)
		@products = Product.all
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
    	@apps = Product.where("name LIKE ?", "%#{params[:query]}%")
  	end

end

app/controllers/user_stores_controller.rb
class UserStoresController < ApplicationController

	def show
    	@product_store = User.first.products
	end
	
	def create
        @store = UserStore.new(user_id: User.first.id, product_id: params[:product_id])
        
        respond_to do |format|
        	if @store.save
            	format.html { redirect_to products_path, flash: { success: 'Produto guardado com sucesso.' }}
          	else
            	format.html { redirect_to products_path, flash: { error: @store.errors.full_messages.first }}
          	end
        end
    end

	def destroy
    	@store = UserStore.find_by_product_id(params[:id])
		@store.destroy
		
		respond_to do |format|
			format.html { redirect_to user_store_path, flash: { success: 'Produto removido com sucesso.' }}
		end
	end

    private
    def user_store_params
    	params.fetch(:product_id, :id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when 'error' then "ui red message"
            when 'success' then "ui green message"
            when 'info' then "ui blue message"
        end
      end
end

app/helpers/apps_helper.rb
module AppsHelper
  require 'digest/md5'

  def product_image(product)
    color = Digest::MD5.hexdigest(product.name)[0..5]
    "https://dummyimage.com/300x300/#{color}/ffffff.png&text=#{product.name}"
  end
end

app/helpers/gift_lists_helper.rb
module GiftListsHelper
end

app/helpers/gift_lists_suggestions_helper.rb
module GiftListsSuggestionsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/user_store_helper.rb
module UserStoreHelper
end

app/views/apps/_app_cards.html.erb
<h2 class="ui orange header"><%= name %></h2>
<div class="ui divider"></div>

<div class="ui four cards">
	<% app_list.each do |app| %>

		<div class="card">
			<div class="image">
				<img src="<%= product_image(app) %>">
			</div>
			<div class="content">
				<div class="header"><%= app.name %></div>
				<div class="meta"><%= app.category %></div>
				<div class="description"><%= truncate app.description, length: 100, seperator: /\w+/ %></div>
			</div>
			<div class="extra content center aligned">
				<div class="ui orange mini horizontal statistic">
					<div class="value">
						R$ <%= number_to_human app.price %>
					</div>
				</div>
			</div>
			<%= link_to add_product_user_stores_path(app.id), method: :post, data: { confirm: 'Deseja Guardar o Produto?' } do %>
				<div class="ui bottom attached button">
					<i class="orange add icon"></i>
					Guardar Produto
				</div>
			<% end %>
		</div>
		
	<% end %>
</div>

app/views/apps/show.html.erb
<div class="ui padded raised segment">
	
	<div class="ui items">
		<div class="item">
			<div class="image">
				<img src="<%= product_image(@app) %>">
			</div>
			<div class="content">
				<h1 class="header"><%= @app.name %></h1>
				<div class="meta">
					<span class="cinema"><%= @app.category %></span>
				</div>
				<div class="meta">
					<span class="version">&nbsp</span>
				</div>
				<div class="meta">
					<span class="release">Adicionado em <%= @app.created_at.strftime("%d/%m/%Y") %></span>
				</div>
				<div class="bottom aligned content">
					<%= button_to 'Guardar Produto', add_product_user_stores_path(@app.id), class: 'ui primary button', data: { confirm: 'Deseja Guardar o Produto?' }  %>
				</div>
			</div>
		</div>
	</div>

	<div class="ui divider"></div>

	<div class="ui three small statistics">
		<div class="statistic">
			<div class="value">
				<i class="small green arrow alternate circle down outline icon"></i> <%= rand(7..160) %>
			</div>
			<div class="label">
				Listas
			</div>
		</div>
		<div class="statistic">
			<div class="value">
				<i class="small yellow star icon"></i> <%= rand(6..10) %>
			</div>
			<div class="label">
				Classificação
			</div>
		</div>
		<div class="statistic">
			<div class="value">
				<i class="small users icon"></i> <%= rand(130..1000) %>
			</div>
			<div class="label">
				Visualizações
			</div>
		</div>
	</div>

	<div class="ui divider"></div>

	<h2 class="header">Descrição</h2>
	<div>
		<p><%= @app.description %></p>
	</div>

	<div class="ui divider"></div>

	<h2 class="header">Fotos do Produto</h2>
	<div style="overflow-x: scroll; display: flex;">
		<img src="https://dummyimage.com/420x320/ff7f7f/333333.png&text=Sample 1">
		<img src="https://dummyimage.com/420x320/7f7fff/333333.png&text=Sample 2">
		<img src="https://dummyimage.com/420x320/7fff7f/333333.png&text=Sample 3">
		<img src="https://dummyimage.com/420x320/7f7f7f/333333.png&text=Sample 4">
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Listas de Aniversário</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%# <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> %>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= javascript_pack_tag 'application' %>
	<%= javascript_include_tag 'application' %>
</head>

<body>
	<div class="ui container">

		<div class="ui stackable menu">
			<a class="header item" href="/">
				<img src="/logo.png">
				<span style="margin-left: 8px;">Listas de Aniversário</span>
			</a>
			<a class="item" href="/">Home</a>
			<%= link_to 'Produtos', products_path, class: 'item'%>

			<div class="right menu">
				<%= link_to 'Minhas Listas', gift_lists_path, class: 'item'%>
				<%= link_to 'Meus Produtos', user_store_path(User.first.id), class: 'item'%>
				<div class="item">
					<div class="ui secondary disabled button">Ajuda</div>
				</div>

				<div class="item">
					<div class="ui primary disabled button">Sair</div>
				</div>
			</div>
		</div>
		
	</div>

	<div class="ui container content">
		<% flash.each do | message_type, message_content | %>
		<% flash.delete(:timedout) %> 
		<div class="<%= flash_class(message_type) %> transition">
			<i class="close closable"></i>
			<div class="header">
				<%= message_content %>
			</div>
		</div>
		<% end %>
	</div>

	<div class="ui container content">
		<%= yield %>
	</div>

</body>

</html>